### ISSUE TITLE
Web Events not working via Remote Manager

### ISSUE THREAD

**Issue by pavledragisic** [macchina-io/macchina.io#108]
#### Expected Behavior
When accessing  Macchina.io Web UI all bundles that are subscribed to Web Events should be notified when  Web Event notify method has been called, and then they can access Web Event data. Bundles subscribed to that event should receive event data unrelated to Web UI connection type (Direct access via IP address in LAN or via macchina.io Remote Manager.

#### Actual Behavior
When accessing Macchina.io Web UI via IP address in LAN Web Events work, and bundles get notified and can access Web Event data. On the other hand when accessing Web UI using Remote Manager bundles that are subscribed don’t get notified and don’t get Web Event data.

#### Steps to Reproduce
Reproducing this issue can be done using Macchina.io _SensorLog_ bundle. _SensorLog_ bundle is using Web Events to monitor sensor value changes. To see if bundle is receiving Web Events we can just add one console.log in the function that is handling Web Event. 

In file macchina.io/samples/SensorLog/bundle/webapp/js/controllers.js / on the line 71 method _onNotify_ should look like this:

WebEvent.onNotify = function(evt) {
        for (var id in $scope.sensors)
        {
          if ('sensorlog.' + id == evt.subject)
          {
          	$scope.sensors[id].value = parseFloat(evt.data);
	        console.log("SensorLog Event");
                console.log(evt.data);
          }
        }
        $scope.$apply();
      };

After editing controllers.js recompile _SensorLog_ bundle and start macchina.io. Device running macchina.io should be registered in Remote Manager.

Web UI pages accessed via LAN and Remote Manager are shown bellow. We can see that there is no console log on the page accessed via Remote Manager.

_Web UI accessed via LAN_
![SensorLog Local](https://user-images.githubusercontent.com/32882790/130454828-8882a321-642b-475f-8af8-d4158a1bb20d.PNG)

_Web UI accessed via Remote Manager_
![SensorLog RemoteMngr](https://user-images.githubusercontent.com/32882790/130454834-1920c6e0-85fb-48da-bc0a-463466a5d3e7.PNG)

#### macchina.io Version
macchina-2020.1-release

#### Compiler and Version
gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

#### Operating System and Version
 System information: Linux (4.19.150) on armv7l

**Comment by obiltschnig** [comment]
This is currently a limitation in Remote Manager, as Remote Manager uses the same mechanism. The actual issue is that the request to open the `WebSocket` for `WebEvent` is handled by the Remote Manager server and not forwarded to the device.

**Comment by aleks-f** [comment]
@pavledragisic this functionality does exist, I've needed it and implemented it a while ago, but it is not yet released anywhere

**Comment by aleks-f** [comment]
ok, I didn't know
