### ISSUE TITLE
Cross-compile with external OpenSSL

### ISSUE THREAD

**Issue by zaleksa** [macchina-io/macchina.io#109]
What are the steps to cross-compile macchina.io with built external OpenSSL libraries?

Should I copy OpenSSL header and lib files to macchina.io/platform/openssl directory, or I need to specify INCLUDE and LIB environment variables, or define POCO_EXTERNAL_OPENSSL macro?

Can you provide some example, shell command or similar?

I am going to use ~/armadeus/buildroot/output/build/libopenssl-1.1.1g library.

When I cross-compile macchina.io, following log appears:

In file included from include/Poco/Crypto/Cipher.h:21,
                 from src/Cipher.cpp:15:
include/Poco/Crypto/Crypto.h:28:10: fatal error: openssl/opensslv.h: No such file or directory
   28 | #include <openssl/opensslv.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

macchina.io Version
macchina-2021.1-release

Compiler and Version
gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Operating System and Version
System information: Linux (4.19.150) on armv7l

**Comment by obiltschnig** [comment]
Are you sure that the libraries are in `$(OPENSSL_DIR)` and not in `$(OPENSSL_DIR)/lib`.

**Comment by zaleksa** [comment]
I added SHLIBFLAGS  = -L$(OPENSSL_DIR) at the end of Compiler and Linker Flags. Now it can compile libPocoCrypto.so (~/macchina.io/platform/lib/Linux/armv7a/).

But new error occured:

* Compiling src/MQTTClient.c (release, shared)
src/Base64.c:43:10: fatal error: openssl/bio.h: No such file or directory
   43 | #include <openssl/bio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/home/aleksa/macchina.io/platform/build/rules/compile:72: /home/aleksa/macchina.io/protocols/MQTT/Paho/obj/Linux/armv7a/release_shared/Base64.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from src/Clients.c:24:
src/Clients.h:31:10: fatal error: openssl/ssl.h: No such file or directory
   31 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.


Those missing headers are in OPENSSL_DIR/include/openssl/ directory.

![Screenshot from 2021-10-16 12-25-18](https://user-images.githubusercontent.com/44501572/137583852-83cf0c5c-705b-4739-b3e6-5799180a957c.png)

Please look at config file, maybe I'm missing something:
[dg100.txt](https://github.com/macchina-io/macchina.io/files/7357375/dg100.txt)


Steps I took to cross-compile macchina.io are:

`$ sudo apt install build-essential libssl-dev python`
`$ make -s -j4 hosttools`
`$ export CROSS_COMPILE=arm-none-linux-gnueabihf`
`$ export PATH=~/armadeus/buildroot/output/host/opt/ext-toolchain/bin/:$PATH`
`$ make -s -j4 LINKMODE=SHARED DEFAULT_TARGET=shared_release POCO_CONFIG=dg100 OPENSSL_DIR=~/armadeus/buildroot/output/build/libopenssl-1.1.1l`

$ arm-none-linux-gnueabihf-gcc --version
arm-none-linux-gnueabihf-gcc (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.2.1 20201103
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


NOTE: I do succeed to cross-compile macchina.io but only if I manually copy OpenSSL headers and libs to macchina.io (headers to ~/macchina.io/platform/Crypto/include, libs to ~/macchina.io/platform/lib/Linux/armv7a), which is dirty way, especially for git version control.

Please look at this log file, I'm getting lot of warning messages while compiling V8 engine:
[compile.log](https://github.com/macchina-io/macchina.io/files/7357400/compile.log)


Thank you in advance
Aleksandar

**Comment by obiltschnig** [comment]
Unfortunately you'll have to live with the warnings when compiling V8. Or specifically disable them in your build configuration file by adding `-Wnodeprecated-copy` to `CXXFLAGS`.

**Comment by zaleksa** [comment]
Finally I succeeded to cross compile macchina.io with external OpenSSL libraries.

At first I followed your advice to add -I$(OPENSSL_DIR)/include to CFLAGS and CXXFLAGS, -L$(OPENSSL_DIR) to SHLIBFLAGS or SYSLIBS. This way it compiled without errors.

But, then I saw in 'Darwin-clang-libc++' config file that -I$(OPENSSL_DIR)/include is added to SYSFLAGS, and -L$(OPENSSL_DIR)/lib to SYSLIBS. So I tried this way (omitted /lib) and it compiled.

So finally config file looks like this:
[DG100.txt](https://github.com/macchina-io/macchina.io/files/7359708/DG100.txt)


Considering V8 compiling, I can live with the warnings. My concern was if I'm doing something wrong, like using wrong gcc version or similiar. Alongside -Wdeprecated-copy warning, there are few more, like:

-Wclass-memaccess
-Wcast-function-type
-Wimplicit-fallthrough=
-Wdeprecated-declarations
-Wstringop-overflow=
-Wcpp

So I left all warnings to print out while compiling.

Please advise me if you see some issues considering DG100 config file or V8 compile warnings.

Thank you very much,
Aleksandar
