### ISSUE TITLE
Update bundled V8 to a more recent release.

### ISSUE THREAD

**Issue by obiltschnig** [macchina-io/macchina.io#11]
While the bundled V8 release (3.25.28.18) is doing a good job in terms of stability, it's not up to date with ES 6 support. For release 1.0, we should consider updating to a newer release.

**Comment by obiltschnig** [comment]
For 1.0, the V8 release will be v8-3.28.4. After that, we will update to a more current release, which will probably require some significant changes to how we build V8, as newer V8 releases do not build out of the box with the current build system.

**Comment by xpete** [comment]
Can you give a higher priority to this? 
v8-3.28.4 doesn't build with gcc 6 and uses function from openssl that are deprecated in openssl 1.1.

**Comment by aleks-f** [comment]
I'll start working on it soon, tentative ETA sometime in June.

**Comment by obiltschnig** [comment]
There's now a feature/v8-6.1 branch, based on V8 release 6.1 (same as used in current node.js 8.9.1 LTS). Needs a bit more work (testing, cross-compiling), but will be part of 1.0 release.

**Comment by obiltschnig** [comment]
After upgrading V8 there's a problem with a GC-related hang in V8.

Details: https://bugs.chromium.org/p/v8/issues/detail?id=7207

**Comment by obiltschnig** [comment]
Was indeed a V8 issue (https://bugs.chromium.org/p/v8/issues/detail?id=6933). Backported fix from upstream in 688829243ce3495dcdb69bcb55f6a8f9e4a7f9f9
