### ISSUE TITLE
How to share data between bundle activator and HTTP handler

### ISSUE THREAD

**Issue by aleks-f** [macchina-io/macchina.io#14]
OK, so I keep my user objects in the bundle activator. I would also like to be able to access those objects from the HTTP handler factory registered as an extension point. Since both activator and handler are instantiated by the OSP environment, the only way to share data between them seems to be through a global variable (ugly). Is there a better way short of launching my own web server from bundle activator?

**Comment by obiltschnig** [comment]
Think Services!

Create a Service object (that's holding and providing access to all your user objects) and register it in the Service Registry.

You may also want to think about making some or all your user objects Service objects themselves. Also think about first creating service interfaces, then make your user objects implement these interfaces.

**Comment by aleks-f** [comment]
I guess I could do that. I've done services before but it was for system-wide generic functionality, I never did that for user application objects. Thanks.
