### ISSUE TITLE
MQTT Client Screen

### ISSUE THREAD

**Issue by domahoneyii** [macchina-io/macchina.io#17]
1) I can't view the client's feed.

2) I subscribed to macchina.io using MQTT-Lens to do a subscription to tcp:iot.eclipse.org:1883.  The screen always says "no scubscription"

**Comment by obiltschnig** [comment]
macchina.io does not include an MQTT broker, just a client. Therefore, the MQTT web page will only show the topics the macchina.io clients are subscribed to at the various broker connections. To subscribe to a topic, use the subscribe() or subscribeMany() methods of MQTTClient and handle the messageArrived event.
