### ISSUE TITLE
MQTT Subscription Question

### ISSUE THREAD

**Issue by domahoneyii** [macchina-io/macchina.io#18]
How do I expose "tcp://iot.eclipse.org:1883" to the external network?
Do I need to use a MQTT broker like mosquitto?

Thanks for the help,

Dan

**Comment by obiltschnig** [comment]
Could you explain in more detail what you want to achieve?

**Comment by domahoneyii** [comment]
The lab that I am building is using flowthings.io for data collection.  I
want flowthings to subscribe to macchina MQTT output.

On Tue, Jul 28, 2015 at 3:37 PM, Günter Obiltschnig <
notifications@github.com> wrote:

> Could you explain in more detail what you want to achieve?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macchina-io/macchina.io/issues/18#issuecomment-125731712>
> .
>



-- 
Lead Engineer, IOT Impact Labs

Program Director, SoCo Coding Foundry, http://sococodingfoundry.org
Executive Committee, SouthCoast STEM & Innovation Consortium,
http://socostem.org

Chief Geek, The Virtual Sail Loft, http://thevirtualsailloft.com

dan@thevirtualsailloft.com
(508) 415-1146

**Comment by obiltschnig** [comment]
Dan,

it seems that if you want to connect flowthings.io, you'll need to run your own MQTT broker like mosquitto. You'll have to run it on a server that's reachable over the internet, as the flowthings.io client needs to connect to it. For first testing, using a public test server like tcp://test.mosquitto.org:1883 or tcp://iot.eclipse.org:1883 will probably work as well. Of course things would be much easier if flowthings.io had their own MQTT broker.
Use the macchina.io MQTT client to publish data to a topic of your choice on the MQTT broker, then configure the flowthings.io MQTT client to subscribe to that topic. 

Günter

**Comment by domahoneyii** [comment]
Thanks for the response.  That is what I figure; just making sure.

Macchina.io is a great product; I psyched to see all the different ways I
can use it.

On Wed, Jul 29, 2015 at 3:33 AM, Günter Obiltschnig <
notifications@github.com> wrote:

> Dan,
>
> it seems that if you want to connect flowthings.io, you'll need to run
> your own MQTT broker like mosquitto. You'll have to run it on a server
> that's reachable over the internet, as the flowthings.io client needs to
> connect to it. For first testing, using a public test server like tcp://
> test.mosquitto.org:1883 or tcp://iot.eclipse.org:1883 will probably work
> as well. Of course things would be much easier if flowthings.io had their
> own MQTT broker.
> Use the macchina.io MQTT client to publish data to a topic of your choice
> on the MQTT broker, then configure the flowthings.io MQTT client to
> subscribe to that topic.
>
> Günter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macchina-io/macchina.io/issues/18#issuecomment-125869859>
> .
>



-- 
Lead Engineer, IOT Impact Labs

Program Director, SoCo Coding Foundry, http://sococodingfoundry.org
Executive Committee, SouthCoast STEM & Innovation Consortium,
http://socostem.org

Chief Geek, The Virtual Sail Loft, http://thevirtualsailloft.com

dan@thevirtualsailloft.com
(508) 415-1146
