### ISSUE TITLE
Communication Between two Bundle

### ISSUE THREAD

**Issue by manthanrtilva** [macchina-io/macchina.io#20]
Hi,
I have two bundle, One is websocket client which communicate to server(send status of all devices to server and execute any command from server). And another bundle which fetch data from sensors. Sensor bundle have some configuration like fetch interval, fetch data etc. Now I wants, when I received command from server, as per command I want to update fetch Interval or other parameter. I had seen this can be done using js by setPorperty method, but I need to do same using C++ code. 
Please suggest some method for it.

Thanks in advance.

**Comment by obiltschnig** [comment]
In the sensor bundle, provide a service for setting configuration properties, and register that service with the OSP ServiceRegistry. The other bundle can then use the ServiceRegistry to find the configuration service and invoke its methods. See http://macchina.io/docs/00150-OSPTutorial.html and http://macchina.io/docs/00300-OSPServiceRegistry.html for more information.

Another way (easier to implement, but less dynamic) would be to use the OSP PreferencesService (http://macchina.io/docs/00350-OSPStandardServices.html) to store configuration parameters. The communication bundle can change the configuration properties of the sensor bundle using the PreferencesService, and then stop and restart the sensor bundle, thus causing it to reload its confguration properties and reconfigure itself.

**Comment by manthanrtilva** [comment]
Hi Its works great. I had figure out some other way to do this thing. But you point out more clean and simple way to do thing.

Thanks.
