### ISSUE TITLE
Paho needs -D_GNU_SOURCE on Linux

### ISSUE THREAD

**Issue by mcirsta** [macchina-io/macchina.io#23]
On my Linux distro I couldn't get Paho to compile unless it had the -D_GNU_SOURCE flag defined. If this wasn't defined it didn't know the addrinfo type which is guarder by 

# ifdef __USE_GNU

  struct addrinfo *ar_result;	/* Pointer to result.  */

inf the netdb.h file.

This file belongs to glibc 2.22 on my system.

**Comment by obiltschnig** [comment]
Interesting - haven't seen this so far. What Linux distro are you using?

**Comment by mcirsta** [comment]
A less known one, Frugalware. For me it doesn't work without this. I think this might be due to a newer glibc though, no sure how it might work on other distros if they have the same glibc , maybe if addrinfo is defined in a different file ?
 This might happen in Arch too as they use newer versions of glibc too.

**Comment by Bjoe** [comment]
Hm sorry, duplicate: see [Compile error in Paho: addrinfo incomplete type on Linux ](https://github.com/macchina-io/macchina.io/issues/38) for more information.
