### ISSUE TITLE
Using OSPSubsystem into a Shared library

### ISSUE THREAD

**Issue by BorisFaz** [macchina-io/macchina.io#27]
Hello.
I would know if it is possible to use OSP into a shared library without using a class derived from poco application. Is it necessary to register the OSPSubsystem into an application in order to use it?
Thank you.

**Comment by obiltschnig** [comment]
You can use OSP without Poco::Util::[Server]Application and OSPSubsystem as well. OSPSubsystem is just a helper class that initialises OSP, using the application's configuration file. If you do all the steps that OSPSubsystem does yourself you don't have to use OSPSubsystem.

**Comment by BorisFaz** [comment]
Ok. Perfect! Thank you very much!
