### ISSUE TITLE
Configuration issue generating stubs

### ISSUE THREAD

**Issue by jptcarreira** [macchina-io/macchina.io#28]
I was creating a new Device class, but was very difficult to understand why the generated stubs didn't extend the right classes...
Took a lot to discover the trick.... or the right configuration.

I suggest to change OSP to true by default in file devices/Devices/RemoteGen.xml and add the flowing:

			<osp>
				<enable>true</enable>
			</osp>

Thnks,
JP

**Comment by obiltschnig** [comment]
good point
