### ISSUE TITLE
POCO Library issue

### ISSUE THREAD

**Issue by palade** [macchina-io/macchina.io#31]
Do poco libraries need to be installed before building macchina or come together with this project?
After building the project and try to run it, I get the following error:

> error while loading shared libraries: libPocoOSP.so

**Comment by obiltschnig** [comment]
No, POCO is included in macchina.io. Have you set LD_LIBRARY_PATH correctly?

**Comment by palade** [comment]
Deleted everything, and re-build it, and now works. Thank you for your help!

**Comment by Sultan91** [comment]
@palade  Could you clarify what should written:  export LD_LIBRARY_PATH=`pwd`/platform/lib/Linux/x86_64
Is 'pwd' thing should be replaced with present working directory or we should leave it as it is?

**Comment by palade** [comment]
$PWD is the current working directory. Can you try LD_LIBRARY_PATH=$PWD/platform/lib/Linux/x86_64? otherwise, just embed the full path.

**Comment by Sultan91** [comment]
Yes, I get it thanks!
