### ISSUE TITLE
integrate UPM/MRAA 

### ISSUE THREAD

**Issue by boonpin1975** [macchina-io/macchina.io#33]
hi ,

 is there possible to integrate the sensor middleware https://github.com/intel-iot-devkit/mraa
 https://github.com/intel-iot-devkit/upm into macchina ? 

 thanks ...

**Comment by obiltschnig** [comment]
Planned, see #12. There is no generic way to integrate UPM devices into macchina.io, as UPM does not have a standard device programming model which could be mapped to macchina's.
