### ISSUE TITLE
could not find Sample directory in the OSP  source tree. 

### ISSUE THREAD

**Issue by MadhusudhanaHV** [macchina-io/macchina.io#34]
Hi,
Please note that I  could not find the source code, project files and makefiles for the tutorials in the **samples** directory in the **OSP source tree**. The **sample** directory is absent in the **OSP source tree**. Kindly let me know where I can get source code, project files and makefiles for the tutorials. Kindly note the url as follows:
http://macchina.io/docs/00150-OSPTutorial.html
Thanks and Regards,
Madhusudhana H V

**Comment by obiltschnig** [comment]
fixed - added the OSP samples
