### ISSUE TITLE
IDE Question

### ISSUE THREAD

**Issue by avalchev** [macchina-io/macchina.io#37]
Hi Gunter,

I'm wondering, which IDE are you using for development under Linux ?

I'm new to C++ world (coming from Java), and the best thing I found is Emacs with irony. Your answer is going to help me to adopt macchina.io development style :)

Thanks a lot.

**Comment by obiltschnig** [comment]
Most of my macchina.io development work is done on OS X, using a plain text editor (BBEdit) and multiple shell windows ;-). From time to time I also use Xcode. On Linux, it's mostly shell + whatever text editor is readily available (can be vi, but usually gedit or something, if a GUI is available). Very occasionally also Eclipse.
