### ISSUE TITLE
Generate client-side Remoting code from IoT::Devices

### ISSUE THREAD

**Issue by Bjoe** [macchina-io/macchina.io#48]
I'm not sure if it is a bug or I did something wrong.
I read the document https://macchina.io/docs/00100-RemotingNGOverview.html about Remote NG and try to generate the client-side Remoting code from macchina.io/devices/Devices (IoT::Devices).

I create a [RemoteGen.xml.zip](https://github.com/macchina-io/macchina.io/files/588848/RemoteGen.xml.zip) and execute the generator as following:
../macchina.io/platform/RemotingNG/RemoteGen/bin/Linux/x86_64/RemoteGenNG -cRemoteGen.xml -DPOCO_BASE=../macchina.io/platform -DPOCO_OSP_DEVICES=../macchina.io/devices/Devices -Cclang

The RemoteGenNG generates for example from the Accelerometer class the expected classes AccelerometerClientHelper, AccelerometerEventSubscriber, AccelerometerProxy and AccelerometerProxyFactory.
But in the AccelerometerEventSubscriber class they generate an inheritance to IoT::Devices::DeviceEventSubscriber instead of Poco::RemotingNG::EventSubscriber. 
In the AccelerometerEventSubscriber header an include of Poco/RemotingNG/EventSubscriber.h exists.
What is going wrong here?

**Comment by obiltschnig** [comment]
It's a bug. Apparently, EventSubscriber code generation is buggy for subclasses.
