### ISSUE TITLE
JSCore is broken with the latest v8

### ISSUE THREAD

**Issue by hakan-akan** [macchina-io/macchina.io#57]
I am trying to get the JS sample to work. It appears that some API has been removed from the v8 that is being used by JSCore. In particular, Wrapper.h is using WeakCallbackData which has been removed according to V8 5.2 API Changes. 

Other issues :
-- Deprecate Isolate::New without parameters.

**Comment by aleks-f** [comment]
v8 will be upgraded and code adjusted soon (ETA mid-June). But what probem exactly are you experiencing? I can build and run the jsrun sample fine

**Comment by hakan-akan** [comment]
> "But what problem exactly are you experiencing?"

If one uses v8 version 6.1. It does not compile and link due to v8 API changes. 

> "I can build and run the jsrun sample fine with the embedded v8"

What version of v8 are you using? Maybe you used some older v8 library to generate JsCore, JsNet, JsData libraries. And used those to generate the JsSample example. Then, it works. At least, it worked for me under Linux.

I downloaded and compiled v8 yesterday. I used Visual Studio 2017. I had to replace the js/v8/include directory with the v8 6.1 include directory due to link issues. Replacing include directory broke compilation of the the JS Core, JS Net, JS Data. I made fairly large number of changes but now it compiles and links. It still does not work, however, I suspect this is due to more subtle v8 changes. If I can look into it today, I should be able to get it to work.

**Comment by aleks-f** [comment]
Yes it wont work with newer v8 versions. As mentioned, there will be some work done soon to bring it up to date.

**Comment by obiltschnig** [comment]
You may want to look at the feature-v8-5.2 branch which contains changes to make JS/Core, etc. work with V8 5.2. Unfortunately, the V8 API changes all the time, which is a Real PITA.

**Comment by obiltschnig** [comment]
Anyway, please contribute back your changes for V8 6.x. Will be much appreciated.

**Comment by hakan-akan** [comment]
Thanks. I checked out the feature-v8-5.2. It appears to be working nicely with v8 version 6.1. It already contains most of the changes I made locally.
