### ISSUE TITLE
DB Session in JS

### ISSUE THREAD

**Issue by JoaoLeiria** [macchina-io/macchina.io#59]
Hello, 

after upgrading to the tag 0.7.0 i can't access the DBSession object in JS (object is not defined). Not even on playground.

I saw you made some changes to this in the Data Session Wrapper in the 0.7.0 release. How do we use the DBSession is JS now?

Thanks in advance,
João

**Comment by obiltschnig** [comment]
The Data (and Net/HTTP) objects have been moved into separate modules (and bundles). So you'll have to import that module:

```
var data = require('data');
var dbSession = new data.DBSession('SQLite', 'test.sqlite');
```

**Comment by JoaoLeiria** [comment]
Thanks for the answer @obiltschnig . 

Already made a pull request, updating the docs: #61
