### ISSUE TITLE
Can't write bundle's properties file

### ISSUE THREAD

**Issue by JoaoLeiria** [macchina-io/macchina.io#62]
Hello, 

I need to read/write in a bundle's .properties file, and can't write in it. 

Given the bundle's context i get it's the properties:

`  Poco::Util::AbstractConfiguration& properties = const_cast<Poco::Util::AbstractConfiguration&>(_pContext->thisBundle()->properties());`

Then i can read the file's content:

`properties.getInt("websession.timeout"); `

All is fine until i try to call the any setter method. Like:

`properties.setInt("websession.timeout", 123);`

An error is thrown:

> Error: Invalid access: Cannot change bundle properties 

What am I doing wrong? 

Thanks in advance,
Best regards,
João

**Comment by obiltschnig** [comment]
As the exception says, bundle properties cannot be written.
