### ISSUE TITLE
Macchina.io Docker  image

### ISSUE THREAD

**Issue by uilianries** [macchina-io/macchina.io#65]
Hi!

I didn't find any Docker image to provide Macchina.io, I searched at hub.docker and github.

Is there any idea to create a official image for Macchina.io? If yes, I can to write such docker recipe.

Regards.

**Comment by obiltschnig** [comment]
A Docker image for macchina.io would definitely be welcome. I can set-up a repo for that if you provide the script ;-)

**Comment by obiltschnig** [comment]
New repo: https://github.com/macchina-io/meta-docker

Please provide pull request when ready.

**Comment by uilianries** [comment]
Thanks! I'll provide ASAP.

Regards.

**Comment by uilianries** [comment]
Done!

I created a new PR [here](https://github.com/macchina-io/meta-docker/pull/1).

**Comment by obiltschnig** [comment]
Thank you!
