### ISSUE TITLE
Issue with on valueChanged event handler

### ISSUE THREAD

**Issue by FatKoala** [macchina-io/macchina.io#76]
Hello,

I have an issue with event handling when i try to attach multiple event handlers, one for every device i have created. After certain amount of callbacks one or multiple handlers just stop working and never get triggered again, despite working properly for about 500 calls. My code runs in playground on raspberry pi 3.
Please find below piece of code that i use to create events.
```js
function attachEvents()
{
    var deviceRefs = serviceRegistry.find('io.macchina.device != ""');
    var tempDevice;
    var eventTrigger;

    for(var i = 0; i < deviceRefs.length ; i++)
    {
        tempDevice = deviceRefs[i].instance();

        tempDevice.on('valueChanged', 
        function(event) {
                logger.information("Event !!! Data: " + event.data);
            }
        );
    }
}
```
Once again, everything works for some time and then some of the events are not triggered anymore despite their values still being changed.
Hope someone can help.
Thanks :)

**Comment by obiltschnig** [comment]
Your code becomes a victim of the V8 garbage collector. You are not keeping any references to your sensor objects, so eventually the GC kicks in and removes them. The culprit is that you're assigning all sensor objects to `tempDevice`, so only the last one will survive. Store your sensor objects in an array to keep them around. Example:

```js
var count = 0;
var sensors = [];
function attachEvents()
{
    var deviceRefs = serviceRegistry.find('io.macchina.device != ""');
    var tempDevice;
    var eventTrigger;

    for (var i = 0; i < deviceRefs.length ; i++)
    {
        tempDevice = deviceRefs[i].instance();
        sensors.push(tempDevice);
        tempDevice.on('valueChanged', 
            function(event) {
                logger.information("Event #%d: Data: %o", count++, event);
            }
        );
    }
}

attachEvents();
```

**Comment by FatKoala** [comment]
Thank you so much for the help. Everything works great now.
