### ISSUE TITLE
compliedirectly  issue on raspberry 3

### ISSUE THREAD

**Issue by KieranYu** [macchina-io/macchina.io#77]
I have met a complle issue on raspberry 3, showing as follow: the same with upper, can this issue fixed yet ? looking forward to get help

===================================================
root@raspberrypi:/home/kieran/macchina/macchina.io# make -s -j8 DEFAULT_TARGET= shared_release
Building V8 for arch arm with flags: library=shared i18nsupport=off werror=no sn apshot=on arm_version=7
ACTION tools_gyp_v8_gyp_v8_snapshot_target_run_mksnapshot /home/kieran/macchin a/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_snapshot/ge ni/snapshot.cc
** Compiling src/SQLiteBundleActivator.cpp (release, shared)
Segmentation fault
tools/gyp/v8_snapshot.target.arm.release.mk:13: recipe for target '/home/kieran/ macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_snap shot/geni/snapshot.cc' failed
make[4]: *** [/home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm .release/obj.target/v8_snapshot/geni/snapshot.cc] Error 139
Makefile:280: recipe for target 'arm.release' failed
make[3]: *** [arm.release] Error 2
cp: cannot stat 'v8-3.28.4/out/arm.release/lib.target/libv8.so': No such file or directory
Makefile:102: recipe for target 'v8install' failed
make[2]: *** [v8install] Error 1
Makefile:271: recipe for target 'JS/V8-libexec' failed
make[1]: *** [JS/V8-libexec] Error 2
make[1]: *** Waiting for unfinished jobs....
** Building dynamic library (release, shared) /home/kieran/macchina/macchina.io/platform/OSP/Data/SQLite/bin/Linux/armv7l/poco.data.sqlite.so
Makefile:78: recipe for target 'clean' failed
make: *** [clean] Error 2
root@raspberrypi:/home/kieran/macchina/macchina.io#

**Comment by obiltschnig** [comment]
You’re running out of memory.

Building with 8 parallel build processes (make -j8) on a Raspberry Pi is a bit too much. I’d go with -j2 at most.

**Comment by KieranYu** [comment]
i 'm suspecious of this, and i create a swapfile with 4G,  still not enough ?  so how many memory need for a parallel running ?

**Comment by KieranYu** [comment]
this thing happened again, even if i used j2, and during the complie, i keep my eye on checking "top" and "free -m", the memory is enough. 

================================================================
  CXX(target) /home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_nosnapshot/src/snapshot-empty.o
** Compiling src/TransportFactory.cpp (release, shared)
  AR(target) /home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/tools/gyp/libv8_nosnapshot.a
  CXX(target) /home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/mksnapshot/src/mksnapshot.o
** Compiling src/PlainClientAuthenticator.cpp (release, shared)
** Compiling src/SCRAMClientAuthenticator.cpp (release, shared)
  LINK(target) /home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/mksnapshot
** Compiling src/SCRAMAuthenticator.cpp (release, shared)
  ACTION tools_gyp_v8_gyp_v8_snapshot_target_run_mksnapshot /home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_snapshot/geni/snapshot.cc
Segmentation fault
tools/gyp/v8_snapshot.target.arm.release.mk:13: recipe for target '/home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_snapshot/geni/snapshot.cc' failed
make[4]: *** [/home/kieran/macchina/macchina.io/platform/JS/V8/v8-3.28.4/out/arm.release/obj.target/v8_snapshot/geni/snapshot.cc] Error 139
Makefile:280: recipe for target 'arm.release' failed
make[3]: *** [arm.release] Error 2
cp: cannot stat 'v8-3.28.4/out/arm.release/lib.target/libv8.so': No such file or directory
Makefile:102: recipe for target 'v8install' failed
make[2]: *** [v8install] Error 1
Makefile:271: recipe for target 'JS/V8-libexec' failed
make[1]: *** [JS/V8-libexec] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/6/map:60:0,
                 from /home/kieran/macchina/macchina.io/platform/RemotingNG/include/Poco/RemotingNG/AttributedObject.h:28,
                 from /home/kieran/macchina/macchina.io/platform/RemotingNG/include/Poco/RemotingNG/Credentials.h:23,
                 from /home/kieran/macchina/macchina.io/platform/RemotingNG/include/Poco/RemotingNG/Authenticator.h:24,
                 from include/Poco/RemotingNG/TCP/SCRAMAuthenticator.h:24,
                 from src/SCRAMAuthenticator.cpp:17:
/usr/include/c++/6/bits/stl_tree.h: In member function ‘void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_erase_aux(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator) [with _Key = Poco::Timestamp; _Val = std::pair<const Poco::Timestamp, unsigned int>; _KeyOfValue = std::_Select1st<std::pair<const Poco::Timestamp, unsigned int> >; _Compare = std::less<Poco::Timestamp>; _Alloc = std::allocator<std::pair<const Poco::Timestamp, unsigned int> >]’:
/usr/include/c++/6/bits/stl_tree.h:2268:5: note: parameter passing for argument of type ‘std::_Rb_tree<Poco::Timestamp, std::pair<const Poco::Timestamp, unsigned int>, std::_Select1st<std::pair<const Poco::Timestamp, unsigned int> >, std::less<Poco::Timestamp>, std::allocator<std::pair<const Poco::Timestamp, unsigned int> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Poco::Timestamp, unsigned int> >}’ will change in GCC 7.1
     _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h: In member function ‘void Poco::ExpireStrategy<TKey, TValue>::onRemove(const void*, const TKey&) [with TKey = unsigned int; TValue = Poco::RemotingNG::TCP::SCRAMAuthenticator::Conversation]’:
/usr/include/c++/6/bits/stl_tree.h:1047:2: note: parameter passing for argument of type ‘std::_Rb_tree<Poco::Timestamp, std::pair<const Poco::Timestamp, unsigned int>, std::_Select1st<std::pair<const Poco::Timestamp, unsigned int> >, std::less<Poco::Timestamp>, std::allocator<std::pair<const Poco::Timestamp, unsigned int> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Poco::Timestamp, unsigned int> >}’ will change in GCC 7.1
  _M_erase_aux(__position);
  ^~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h: In member function ‘void Poco::ExpireStrategy<TKey, TValue>::onAdd(const void*, const Poco::KeyValueArgs<TKey, TValue>&) [with TKey = unsigned int; TValue = Poco::RemotingNG::TCP::SCRAMAuthenticator::Conversation]’:
/usr/include/c++/6/bits/stl_tree.h:1047:2: note: parameter passing for argument of type ‘std::_Rb_tree<Poco::Timestamp, std::pair<const Poco::Timestamp, unsigned int>, std::_Select1st<std::pair<const Poco::Timestamp, unsigned int> >, std::less<Poco::Timestamp>, std::allocator<std::pair<const Poco::Timestamp, unsigned int> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Poco::Timestamp, unsigned int> >}’ will change in GCC 7.1
  _M_erase_aux(__position);
  ^~~~~~~~~~~~
/usr/include/c++/6/bits/stl_tree.h: In member function ‘void Poco::AbstractStrategy<TKey, TValue>::onUpdate(const void*, const Poco::KeyValueArgs<TKey, TValue>&) [with TKey = unsigned int; TValue = Poco::RemotingNG::TCP::SCRAMAuthenticator::Conversation]’:
/usr/include/c++/6/bits/stl_tree.h:1047:2: note: parameter passing for argument of type ‘std::_Rb_tree<Poco::Timestamp, std::pair<const Poco::Timestamp, unsigned int>, std::_Select1st<std::pair<const Poco::Timestamp, unsigned int> >, std::less<Poco::Timestamp>, std::allocator<std::pair<const Poco::Timestamp, unsigned int> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const Poco::Timestamp, unsigned int> >}’ will change in GCC 7.1
  _M_erase_aux(__position);
  ^~~~~~~~~~~~
** Building shared library (release) /home/kieran/macchina/macchina.io/platform/lib/Linux/armv7l/libPocoRemotingNGTCP.so.48
Makefile:78: recipe for target 'clean' failed
make: *** [clean] Error 2
root@raspberrypi:/home/kieran/macchina/macchina.io#

**Comment by KieranYu** [comment]
it's the snapshot should not be included in the complie, used as following command:( to skip sapshot) 
    $ make -s -j2 V8_NOSNAPSHOT=1 DEFAULT_TARGET=shared_release

now it can complie all, but when i run the server, it shows up: can not find the xx.so, and also after complie it doesn't generate the codeCache folder, i manaul create the codeCache folder, and copy the lib
 from xx/macchina.io/lib/Linux/armv7l/*.so and  xx/macchina.io/platform/lib/Linux/armv7l/*.so to codeCache foler, then it runs ok now

by the way, issued offered with title Building for Raspberry Pi 2 (armv7) on Ubuntu 17.04 fails #55
can also be helpful.

thanks for the help from the developers
