### ISSUE TITLE
Compilation error on Debian 9, gcc 6.3

### ISSUE THREAD

**Issue by gocarlos** [macchina-io/macchina.io#87]
#### Expected Behavior
Compile and run using the instructions on the README.md

#### Actual Behavior
Fails to compile on Debian 9

#### Steps to Reproduce

```bash
    $ git clone https://github.com/macchina-io/macchina.io.git
    $ cd macchina.io
    $ git checkout master
    $ make -s -j8 DEFAULT_TARGET=shared_release
```
#### macchina.io Version

master

#### Compiler and Version

gcc 6.3

#### Operating System and Version

Debian 9

#### Other Relevant Information

[compilation2.log](https://github.com/macchina-io/macchina.io/files/2178854/compilation2.log)

cc/ @bufferoverflow

**Comment by obiltschnig** [comment]
Please use the develop branch, current master uses outdated V8.

**Comment by gocarlos** [comment]
Outdated issue
