### ISSUE TITLE
Cannot make on Jetson TX2, Ubuntu 16.04 

### ISSUE THREAD

**Issue by Miroslav1993** [macchina-io/macchina.io#89]
Following the steps from the Readme file, the make process fails on a recently flashed Jetson TX2 board running Ubuntu 16.04 with the following error:

Makefile:63: *** Unknown target architecture.  Stop.
Makefile:271: recipe for target 'JS/V8-libexec' failed
make[1]: *** [JS/V8-libexec] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:76: recipe for target 'clean' failed
make: *** [clean] Error 2

I have not found any info on a similar error online.

**Comment by obiltschnig** [comment]
Looks like an issue with passing the correct build parameters to the V8 build system.

Could you provide more information? Specifically, output of `uname -a` and how you did the build (native or cross-compile).

**Comment by obiltschnig** [comment]
Could you try current develop branch. I have just added some code to detect aarch64 and pass the proper (hopefully) flags to V8 build system.

**Comment by Miroslav1993** [comment]
Tried making with your latest commit, at first it failed but it just needed sudo, and then it passed.

Unfortunately, upon trying to start macchina, the following error occurs:

`bin/Linux/aarch64/macchina: error while loading shared libraries: libPocoOSP.so.2: cannot open shared object file: No such file or directory`

Should I make a new issue about this?

**Comment by obiltschnig** [comment]
Hm, it should not be necessary to build macchina.io with `sudo`. So it could be a permissions issue. I'd recommend cleaning everything and rebuilding from scratch, without `sudo`. Also, verify that `LD_LIBRARY_PATH` is really set and exported correctly.

**Comment by Miroslav1993** [comment]
Cleaning and rebuilding from scratch worked! Thank you for the assistance.
