### ISSUE TITLE
Sorting data in Settings webUI of macchina.io

### ISSUE THREAD

**Issue by zaleksa** [macchina-io/macchina.io#99]
Actual behavior of Settings bundle in macchina.io is that all data is sorted in alphabetical order.

Is it possible to avoid this, i.e. to sort the data as it is in the property file?

I am using changed Settings bundle to load and save settings from xml file, so it is important for me to keep order in xml fajl. Now, the data, which are sort in xml file in some logical order, is loaded in webUI in alphabetical order, and saved also in alphabetical order in xml file, which is not behavior that I expect.

Thanks in advance,

Aleksandar

**Comment by obiltschnig** [comment]
This is not possible, due to the way the Settings app works. Btw, the settings bundle does not work with an XML file, but with a .properties file.
